### ISSUE TITLE
NoSuchNodeError: group ``/`` does not have a child named ``//data``

### ISSUE THREAD

**Issue by kdn82** [PV-Lab/bayesim#1]
I am getting an error in ideal_diode when saving in "dd.io.save('obs_data.h5',data)", see error below. When using the obs_data.h5 file supplied with example, the same error is generated further by "m.run()". So I cannot run an ideal_diode example. I am running Python 3 in Jupiter installed with Anaconda3 on Windows 7 enterprise.
Error:
NoSuchNodeError                           Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\pytables.py in get_node(self, key)
   1159                 key = '/' + key
-> 1160             return self._handle.get_node(self.root, key)
   1161         except _table_mod.exceptions.NoSuchNodeError:

C:\ProgramData\Anaconda3\lib\site-packages\tables\file.py in get_node(self, where, name, classname)
   1643             nodepath = join_path(basepath, name or '') or '/'
-> 1644             node = where._v_file._get_node(nodepath)
   1645         elif isinstance(where, (six.string_types, numpy.str_)):

C:\ProgramData\Anaconda3\lib\site-packages\tables\file.py in _get_node(self, nodepath)
   1598 
-> 1599         node = self._node_manager.get_node(nodepath)
   1600         assert node is not None, "unable to instantiate node ``%s``" % nodepath

C:\ProgramData\Anaconda3\lib\site-packages\tables\file.py in get_node(self, key)
    436         if self.node_factory:
--> 437             node = self.node_factory(key)
    438             self.cache_node(node, key)

C:\ProgramData\Anaconda3\lib\site-packages\tables\group.py in _g_load_child(self, childname)
   1180         # Is the node a group or a leaf?
-> 1181         node_type = self._g_check_has_child(childname)
   1182 

C:\ProgramData\Anaconda3\lib\site-packages\tables\group.py in _g_check_has_child(self, name)
    397                 "group ``%s`` does not have a child named ``%s``"
--> 398                 % (self._v_pathname, name))
    399         return node_type

NoSuchNodeError: group ``/`` does not have a child named ``//data``

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-9-0c5ada699526> in <module>
     33 # save them to HDF5
     34 data = pd.DataFrame.from_records(data=data,columns=['V','T','J','uncertainty'])
---> 35 dd.io.save('obs_data.h5',data)
     36 
     37 # these next few lines are for generating the plot

C:\ProgramData\Anaconda3\lib\site-packages\deepdish\io\hdf5io.py in save(path, data, compression)
    594         else:
    595             _save_level(h5file, group, data, name='data',
--> 596                         filters=filters, idtable=idtable)
    597             # Mark this to automatically unpack when loaded
    598             group._v_attrs[DEEPDISH_IO_UNPACK] = True

C:\ProgramData\Anaconda3\lib\site-packages\deepdish\io\hdf5io.py in _save_level(handler, group, level, name, filters, idtable)
    251     elif _pandas and isinstance(level, (pd.DataFrame, pd.Series, pd.Panel)):
    252         store = _HDFStoreWithHandle(handler)
--> 253         store.put(group._v_pathname + '/' + name, level)
    254 
    255     elif isinstance(level, (sparse.dok_matrix,

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\pytables.py in put(self, key, value, format, append, **kwargs)
    887             format = get_option("io.hdf.default_format") or 'fixed'
    888         kwargs = self._validate_format(format, kwargs)
--> 889         self._write_to_group(key, value, append=append, **kwargs)
    890 
    891     def remove(self, key, where=None, start=None, stop=None):

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\pytables.py in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
   1365     def _write_to_group(self, key, value, format, index=True, append=False,
   1366                         complib=None, encoding=None, **kwargs):
-> 1367         group = self.get_node(key)
   1368 
   1369         # remove the node if we are not appending

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\pytables.py in get_node(self, key)
   1159                 key = '/' + key
   1160             return self._handle.get_node(self.root, key)
-> 1161         except _table_mod.exceptions.NoSuchNodeError:
   1162             return None
   1163 

AttributeError: 'NoneType' object has no attribute 'exceptions'

**Comment by kdn82** [comment]
Update: the same error appears when runing ideal_diode in cloud binder from page https://pv-lab.github.io/bayesim/_build/html/examples.html

**Comment by rkurchin** [comment]
All fixed! The Binder works now too.

Rachel C. Kurchin
PhD Candidate, Materials Science & Engineering
MIT Photovoltaics Research Laboratory <http://pv.mit.edu/>
rkurchin.github.io

**Comment by rkurchin** [comment]
Okay, it's actually a Pandas thing. I have a fix, I just need to figure out
the cleanest way to release it into the code. Hopefully will be resolved by
the end of today!

Thanks again for pointing this out!

Rachel

Rachel C. Kurchin
PhD Candidate, Materials Science & Engineering
MIT Photovoltaics Research Laboratory <http://pv.mit.edu/>
rkurchin.github.io

**Comment by rkurchin** [comment]
Hi Dmitry,

I'm starting to look at this – my best guess is it has to do with the
latest update to the pytables package. Will update you as I figure out more.

Rachel

Rachel C. Kurchin
PhD Candidate, Materials Science & Engineering
MIT Photovoltaics Research Laboratory <http://pv.mit.edu/>
rkurchin.github.io

**Comment by rkurchin** [comment]
Okay, the version that you get with pip install should work properly now
but in the process I've broken the Binder. Still working on fixing that
again...but in the meantime you should certainly be able to clone the
repository and run it locally in Jupyter.

Rachel C. Kurchin
PhD Candidate, Materials Science & Engineering
MIT Photovoltaics Research Laboratory <http://pv.mit.edu/>
rkurchin.github.io

**Comment by kdn82** [comment]
Rachel, thanks, I'll try it out and let you know if there will be any
further issues.

Thanks again,
Dmitry
